
name: cron used

# Controls  the workflow will run in every 5 min 

on:
  schedule:
     - cron: "*/5 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 
        
      - name: Terraform Init
        uses: hashicorp/terraform-github-actions/init@v0.4.0   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions/validate@v0.3.7 
        
      - name: Terraform Apply
        uses: hashicorp/terraform-github-actions/apply@v0.4.0
                   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'
      
